drop table if exists wqp.org_data_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'org_data');
drop table if exists wqp.project_data_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'project_data');
drop table if exists wqp.station_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'station');
drop table if exists wqp.bio_hab_metric_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'bio_hab_metric');
drop table if exists wqp.activity_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'activity');
drop table if exists wqp.act_metric_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'act_metric');
drop table if exists wqp.result_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'result');
drop table if exists wqp.r_detect_qnt_lmt_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'r_detect_qnt_lmt');
drop table if exists wqp.prj_ml_weighting_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'prj_ml_weighting');

drop table if exists wqp.activity_sum_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'activity_sum');
drop table if exists wqp.result_sum_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'result_sum');
drop table if exists wqp.org_grouping_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'org_grouping');
drop table if exists wqp.ml_grouping_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'ml_grouping');
drop table if exists wqp.organization_sum_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'organization_sum');
drop table if exists wqp.station_sum_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'station_sum');

drop table if exists wqp.assemblage_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'assemblage');
drop table if exists wqp.char_name_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'char_name');
drop table if exists wqp.char_type_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'char_type');
drop table if exists wqp.country_testsr cascade;
select create_swap_table ('nwis', 'wqp', 'country');
drop table if exists wqp.county_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'county');
drop table if exists wqp.monitoring_loc_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'monitoring_loc');
drop table if exists wqp.organization_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'organization');
drop table if exists wqp.project_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'project');
drop table if exists wqp.project_dim_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'project_dim');
drop table if exists wqp.sample_media_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'sample_media');
drop table if exists wqp.site_type_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'site_type');
drop table if exists wqp.state_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'state');
drop table if exists wqp.taxa_name_swap_nwis cascade;
select create_swap_table ('nwis', 'wqp', 'taxa_name');

