select 
 SITE_ID               ,
 AGENCY_CD             ,
 SITE_NO               ,
 NWIS_HOST             ,
 DB_NO                 ,
 STATION_NM            ,
 DEC_LAT_VA            ,
 DEC_LONG_VA           ,
 COORD_METH_CD         ,
 COORD_ACY_CD          ,
 DISTRICT_CD           ,
 COUNTRY_CD            ,
 STATE_CD              ,
 COUNTY_CD             ,
 LAND_NET_DS           ,
 MAP_SCALE_FC          ,
 ALT_VA                ,
 ALT_METH_CD           ,
 ALT_ACY_VA            ,
 ALT_DATUM_CD          ,
 HUC_CD                ,
 BASIN_CD              ,
 SITE_TP_CD            ,
 replace(replace(SITE_RMKS_TX, char(9), ' '), '\\', '/') AS SITE_RMKS_TX,
 DRAIN_AREA_VA         ,
 CONTRIB_DRAIN_AREA_VA ,
 CONSTRUCTION_DT       ,
 AQFR_TYPE_CD          ,
 AQFR_CD               ,
 NAT_AQFR_CD           ,
 WELL_DEPTH_VA         ,
 HOLE_DEPTH_VA         ,
 SITE_WEB_CD           ,
 DEC_COORD_DATUM_CD    ,
 SITE_CN               ,
 SITE_CR               ,
 SITE_MN               ,
 SITE_MD
from
 SITEFILE;
