CREATE TABLE `QW_SAMPLE` (
  `sample_id` int(11) NOT NULL AUTO_INCREMENT,
  `site_id` int(11) NOT NULL,
  `record_no` char(8) NOT NULL,
  `nwis_host` varchar(12) NOT NULL,
  `db_no` char(2) NOT NULL,
  `qw_db_no` char(2) NOT NULL,
  `sample_web_cd` char(1) NOT NULL,
  `sample_start_dt` datetime NOT NULL,
  `sample_start_display_dt` varchar(19) DEFAULT NULL,
  `sample_start_sg` char(1) NOT NULL DEFAULT '',
  `sample_end_dt` varchar(19) DEFAULT '',
  `sample_end_display_dt` varchar(19) DEFAULT NULL,
  `sample_end_sg` char(1) NOT NULL DEFAULT '',
  `sample_utc_start_dt` datetime DEFAULT NULL,
  `sample_utc_start_display_dt` varchar(19) DEFAULT NULL,
  `sample_utc_end_dt` varchar(19) DEFAULT '',
  `sample_utc_end_display_dt` varchar(19) DEFAULT NULL,
  `sample_start_time_datum_cd` char(6) NOT NULL,
  `medium_cd` char(3) DEFAULT NULL,
  `tu_id` varchar(11) DEFAULT NULL,
  `body_part_id` varchar(11) DEFAULT NULL,
  `sidno_party_cd` char(3) NOT NULL DEFAULT '',
  `nwis_sample_id` char(9) DEFAULT NULL,
  `lab_no` char(7) DEFAULT NULL,
  `project_cd` char(9) DEFAULT NULL,
  `aqfr_cd` char(8) DEFAULT NULL,
  `samp_type_cd` char(1) DEFAULT NULL,
  `sample_lab_cm_tx` varchar(300) DEFAULT NULL,
  `sample_field_cm_tx` varchar(300) DEFAULT NULL,
  `coll_ent_cd` char(8) DEFAULT NULL,
  `anl_stat_cd` char(1) DEFAULT NULL,
  `anl_src_cd` char(1) DEFAULT NULL,
  `anl_type_tx` char(27) DEFAULT NULL,
  `hyd_cond_cd` char(1) DEFAULT NULL,
  `hyd_event_cd` char(1) DEFAULT NULL,
  `tm_datum_rlbty_cd` char(1) DEFAULT NULL,
  `sample_md` datetime DEFAULT NULL,
  `qw_sample_md` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `QW_SAMPLE_PK_IX` (`sample_id`),
  UNIQUE KEY `QW_SAMPLE_AK1_IX` (`site_id`,`qw_db_no`,`record_no`),
  KEY `QW_SAMPLE_IE2_IX` (`nwis_host`,`db_no`,`qw_db_no`,`record_no`),
  KEY `QW_SAMPLE_IE3_IX` (`aqfr_cd`),
  KEY `QW_SAMPLE_IE4_IX` (`sample_start_dt`),
  KEY `QW_SAMPLE_IE5_IX` (`medium_cd`)
) ENGINE=MyISAM AUTO_INCREMENT=354304677 DEFAULT CHARSET=latin1