package gov.acwi.wqp.etl.nwis;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;

import org.springframework.jdbc.core.RowMapper;

public class NwisResultRowMapper implements RowMapper<NwisResult> {
	
	public static final String STATION_ID_COLUMN_NAME = "station_id";
	public static final String SITE_ID_COLUMN_NAME = "site_id";
	public static final String EVENT_DATE_COLUMN_NAME = "event_date";
	public static final String NEMI_URL_COLUMN_NAME = "nemi_url";
	public static final String PARAMETER_CD_COLUMN_NAME = "parameter_cd";
	public static final String ACTIVITY_COLUMN_NAME = "activity";
	public static final String WQPCROSSWALK_COLUMN_NAME = "wqpcrosswalk";
	public static final String SRSNAME_COLUMN_NAME = "srsname";
	public static final String PARM_SEQ_GRP_NM_COLUMN_NAME = "parm_seq_grp_nm";
	public static final String SAMPLE_MEDIA_COLUMN_NAME = "sample_media";
	public static final String ORGANIZATION_COLUMN_NAME = "organization";
	public static final String SITE_TYPE_COLUMN_NAME = "site_type";
	public static final String HUC_COLUMN_NAME = "huc";
	public static final String GOVERNMENTAL_UNIT_CODE_COLUMN_NAME = "governmental_unit_code";
	public static final String ORGANIZATION_NAME_COLUMN_NAME = "organization_name";
	public static final String ACTIVITY_ID_COLUMN_NAME = "activity_id";
	public static final String ACTIVITY_TYPE_CODE_COLUMN_NAME = "activity_type_code";
	public static final String ACTIVITY_MEDIA_SUBDIV_NAME_COLUMN_NAME = "activity_media_subdiv_name";
	public static final String ACTIVITY_START_TIME_COLUMN_NAME = "activity_start_time";
	public static final String ACT_START_TIME_ZONE_COLUMN_NAME = "act_start_time_zone";
	public static final String ACTIVITY_STOP_DATE_COLUMN_NAME = "activity_stop_date";
	public static final String ACTIVITY_STOP_TIME_COLUMN_NAME = "activity_stop_time";
	public static final String ACT_STOP_TIME_ZONE_COLUMN_NAME = "act_stop_time_zone";
	public static final String ACTIVITY_DEPTH_COLUMN_NAME = "activity_depth";
	public static final String ACTIVITY_DEPTH_UNIT_COLUMN_NAME = "activity_depth_uni";
	public static final String ACTIVITY_DEPTH_REF_POINT_COLUMN_NAME = "activity_depth_ref_point";
	public static final String ACTIVITY_UPPER_DEPTH_COLUMN_NAME = "activity_upper_depth";
	public static final String ACTIVITY_UPPER_DEPTH_UNIT_COLUMN_NAME = "activity_upper_depth_unit";
	public static final String ACTIVITY_LOWER_DEPTH_COLUMN_NAME = "activity_lower_depth";
	public static final String ACTIVITY_LOWER_DEPTH_UNIT_COLUMN_NAME = "activity_lower_depth_unit";
	public static final String PROJECT_ID_COLUMN_NAME = "project_id";
	public static final String ACTIVITY_CONDUCTION_ORG_COLUMN_NAME = "activity_conduction_org";
	public static final String ACTIVITY_COMMENT_COLUMN_NAME = "activity_comment";
	public static final String SAMPLE_AQFR_NAME_COLUMN_NAME = "sample_aqfr_name";
	public static final String HYDROLOGIC_CONDITION_NAME_COLUMN_NAME = "hydrologic_condition_name";
	public static final String HYDROLOGIC_EVENT_NAME_COLUMN_NAME = "hydrologic_event_name";
	public static final String SAMPLE_COLLECT_METHOD_ID_COLUMN_NAME = "sample_collect_method_id";
	public static final String SAMPLE_COLLECT_METHOD_CTX_COLUMN_NAME = "sample_collect_method_ctx";
	public static final String SAMPLE_COLLECT_METHOD_NAME_COLUMN_NAME = "sample_collect_method_name";
	public static final String SAMPLE_COLLECT_EQUIP_NAME_COLUMN_NAME = "sample_collect_equip_name";
	public static final String RESULT_ID_COLUMN_NAME = "result_id";
	public static final String REMARK_CD_COLUMN_NAME = "remark_cd";
	public static final String PARM_FRAC_TX_COLUMN_NAME = "parm_frac_tx";
	public static final String FXD_TX_COLUMN_NAME = "fxd_tx";
	public static final String RESULT_VA_COLUMN_NAME = "result_va";
	public static final String PARM_UNT_TX_COLUMN_NAME = "parm_unt_tx";
	public static final String DQI_CD_COLUMN_NAME = "dqi_cd";
	public static final String PARM_STAT_TX_COLUMN_NAME = "parm_stat_tx";
	public static final String RESULT_MD_COLUMN_NAME = "result_md";
	public static final String PARM_WT_TX_COLUMN_NAME = "parm_wt_tx";
	public static final String PARM_TM_TX_COLUMN_NAME = "parm_tm_tx";
	public static final String PARM_TEMP_TX_COLUMN_NAME = "parm_temp_tx";
	public static final String PARM_SIZE_TX_COLUMN_NAME = "parm_size_tx";
	public static final String LAB_STD_VA_COLUMN_NAME = "lab_std_va";
	public static final String RESULT_LAB_CM_TX_COLUMN_NAME = "result_lab_cm";
	public static final String PARM_MEDIUM_TX_COLUMN_NAME = "parm_medium_tx";
	public static final String SAMPLE_TISSUE_TAXONMIC_NAME_COLUMN_NAME = "sample_tissue_taxonmic_name";
	public static final String SAMPLE_TISSUE_ANATOMY_NAME_COLUMN_NAME = "sample_tissue_anatomy_name";
	public static final String METH_CD_COLUMN_NAME = "meth_cd";
	public static final String METH_NM_COLUMN_NAME = "meth_nm";
	public static final String CIT_NM_COLUMN_NAME = "cit_nm";
	public static final String PROTO_ORG_NM_COLUMN_NAME = "proto_org_nm";
	public static final String ANL_DT_COLUMN_NAME = "anl_dt";
	public static final String VAL_QUAL_CD1_NM_COLUMN_NAME = "val_qual_cd1_nm";
	public static final String VAL_QUAL_CD2_NM_COLUMN_NAME = "val_qual_cd2_nm";
	public static final String VAL_QUAL_CD3_NM_COLUMN_NAME = "val_qual_cd3_nm";
	public static final String VAL_QUAL_CD4_NM_COLUMN_NAME = "val_qual_cd4_nm";
	public static final String VAL_QUAL_CD5_NM_COLUMN_NAME = "val_qual_cd5_nm";
	public static final String RPT_LEV_VA_COLUMN_NAME = "rpt_lev_va";
	public static final String RESULT_UNRND_VA_COLUMN_NAME = "result_unrnd_va";
	public static final String PARM_METH_MULTIPLIER_COLUMN_NAME = "parm_meth_multiplier";
	public static final String PARM_MULTIPLIER_COLUMN_NAME = "parm_multiplier";
	public static final String RPT_LEV_CD_COLUMN_NAME = "rpt_lev_cd";
	public static final String WQX_RPT_LEV_NM_COLUMN_NAME = "wqx_rpt_lev_nm";
	public static final String PREP_DT_COLUMN_NAME = "prep_dt";

	@Override
	public NwisResult mapRow(ResultSet rs, int rowNum) throws SQLException {
		NwisResult nwisResult = new NwisResult();
		
		nwisResult.setStationId(rs.getInt(STATION_ID_COLUMN_NAME));
		nwisResult.setSiteId(rs.getString(SITE_ID_COLUMN_NAME));
		nwisResult.setEventDate(LocalDate.parse(rs.getString(EVENT_DATE_COLUMN_NAME)));
		nwisResult.setNemiUrl(rs.getString(NEMI_URL_COLUMN_NAME));
		nwisResult.setParameterCd(rs.getString(PARAMETER_CD_COLUMN_NAME));
		nwisResult.setActivity(rs.getString(ACTIVITY_COLUMN_NAME));
		nwisResult.setWqpcrosswalk(rs.getString(WQPCROSSWALK_COLUMN_NAME));
		nwisResult.setSrsname(rs.getString(SRSNAME_COLUMN_NAME));
		nwisResult.setParmSeqGrpNm(rs.getString(PARM_SEQ_GRP_NM_COLUMN_NAME));
		nwisResult.setSampleMedia(rs.getString(SAMPLE_MEDIA_COLUMN_NAME));
		nwisResult.setOrganization(rs.getString(ORGANIZATION_COLUMN_NAME));
		nwisResult.setSiteType(rs.getString(SITE_TYPE_COLUMN_NAME));
		nwisResult.setHuc(rs.getString(HUC_COLUMN_NAME));
		nwisResult.setGovernmentalUnitCode(rs.getString(GOVERNMENTAL_UNIT_CODE_COLUMN_NAME));
		nwisResult.setOrganizationName(rs.getString(ORGANIZATION_COLUMN_NAME));
		nwisResult.setActivityId(rs.getInt(ACTIVITY_ID_COLUMN_NAME));
		nwisResult.setActivityTypeCode(rs.getString(ACTIVITY_TYPE_CODE_COLUMN_NAME));
		nwisResult.setActivityMediaSubdivName(rs.getString(ACTIVITY_MEDIA_SUBDIV_NAME_COLUMN_NAME));
		nwisResult.setActivityStartTime(rs.getString(ACTIVITY_START_TIME_COLUMN_NAME));
		nwisResult.setActStartTimeZone(rs.getString(ACT_START_TIME_ZONE_COLUMN_NAME));
		nwisResult.setActivityStopDate(rs.getString(ACTIVITY_STOP_DATE_COLUMN_NAME));
		nwisResult.setActivityStopTime(rs.getString(ACTIVITY_STOP_TIME_COLUMN_NAME));
		nwisResult.setActStopTimeZone(rs.getString(ACT_STOP_TIME_ZONE_COLUMN_NAME));
		nwisResult.setActivityDepth(rs.getString(ACTIVITY_DEPTH_COLUMN_NAME));
		nwisResult.setActivityDepthUnit(rs.getString(ACTIVITY_DEPTH_UNIT_COLUMN_NAME));
		nwisResult.setActivityDepthRefPoint(rs.getString(ACTIVITY_DEPTH_REF_POINT_COLUMN_NAME));
		nwisResult.setActivityUpperDepth(rs.getString(ACTIVITY_UPPER_DEPTH_COLUMN_NAME));
		nwisResult.setActivityUpperDepthUnit(rs.getString(ACTIVITY_UPPER_DEPTH_UNIT_COLUMN_NAME));
		nwisResult.setActivityLowerDepth(rs.getString(ACTIVITY_LOWER_DEPTH_COLUMN_NAME));
		nwisResult.setActivityLowerDepthUnit(rs.getString(ACTIVITY_LOWER_DEPTH_UNIT_COLUMN_NAME));
		nwisResult.setProjectId(rs.getString(PROJECT_ID_COLUMN_NAME));
		nwisResult.setActivityConductionOrg(rs.getString(ACTIVITY_CONDUCTION_ORG_COLUMN_NAME));
		nwisResult.setActivityComment(rs.getString(ACTIVITY_COLUMN_NAME));
		nwisResult.setSampleAqfrName(rs.getString(SAMPLE_AQFR_NAME_COLUMN_NAME));
		nwisResult.setHydrologicConditionName(rs.getString(HYDROLOGIC_CONDITION_NAME_COLUMN_NAME));
		nwisResult.setHydrologicEventName(rs.getString(HYDROLOGIC_EVENT_NAME_COLUMN_NAME));
		nwisResult.setSampleCollectMethodId(rs.getString(SAMPLE_COLLECT_METHOD_ID_COLUMN_NAME));
		nwisResult.setSampleCollectMethodCtx(rs.getString(SAMPLE_COLLECT_METHOD_CTX_COLUMN_NAME));
		nwisResult.setSampleCollectMethodName(rs.getString(SAMPLE_COLLECT_METHOD_NAME_COLUMN_NAME));
		nwisResult.setSampleCollectEquipName(rs.getString(SAMPLE_COLLECT_EQUIP_NAME_COLUMN_NAME));
		nwisResult.setResultId(rs.getInt(RESULT_ID_COLUMN_NAME));
		nwisResult.setRemarkCd(rs.getString(REMARK_CD_COLUMN_NAME));
		nwisResult.setParmFracTx(rs.getString(PARM_FRAC_TX_COLUMN_NAME));
		nwisResult.setFxdTx(rs.getString(FXD_TX_COLUMN_NAME));
		nwisResult.setResultVa(rs.getString(RESULT_VA_COLUMN_NAME));
		nwisResult.setParmUntTx(rs.getString(PARM_UNT_TX_COLUMN_NAME));
		nwisResult.setDqiCd(rs.getString(DQI_CD_COLUMN_NAME));
		nwisResult.setParmStatTx(rs.getString(PARM_STAT_TX_COLUMN_NAME));
		nwisResult.setResultMd(rs.getString(RESULT_MD_COLUMN_NAME));
		nwisResult.setParmWtTx(rs.getString(PARM_WT_TX_COLUMN_NAME));
		nwisResult.setParmTmTx(rs.getString(PARM_TM_TX_COLUMN_NAME));
		nwisResult.setParmTempTx(rs.getString(PARM_TEMP_TX_COLUMN_NAME));
		nwisResult.setParmSizeTx(rs.getString(PARM_SIZE_TX_COLUMN_NAME));
		nwisResult.setLabStdVa(rs.getString(LAB_STD_VA_COLUMN_NAME));
		nwisResult.setResultLabCmTx(rs.getString(RESULT_LAB_CM_TX_COLUMN_NAME));
		nwisResult.setParmMediumTx(rs.getString(PARM_MEDIUM_TX_COLUMN_NAME));
		nwisResult.setSampleTissueTaxonmicName(rs.getString(SAMPLE_TISSUE_TAXONMIC_NAME_COLUMN_NAME));
		nwisResult.setSampleTissueAnatomyName(rs.getString(SAMPLE_TISSUE_ANATOMY_NAME_COLUMN_NAME));
		nwisResult.setMethCd(rs.getString(METH_CD_COLUMN_NAME));
		nwisResult.setMethNm(rs.getString(METH_NM_COLUMN_NAME));
		nwisResult.setCitNm(rs.getString(CIT_NM_COLUMN_NAME));
		nwisResult.setProtoOrgNm(rs.getString(PROTO_ORG_NM_COLUMN_NAME));
		nwisResult.setAnlDt(rs.getString(ANL_DT_COLUMN_NAME));
		nwisResult.setValQualCd1Nm(rs.getString(VAL_QUAL_CD1_NM_COLUMN_NAME));
		nwisResult.setValQualCd2Nm(rs.getString(VAL_QUAL_CD2_NM_COLUMN_NAME));
		nwisResult.setValQualCd3Nm(rs.getString(VAL_QUAL_CD3_NM_COLUMN_NAME));
		nwisResult.setValQualCd4Nm(rs.getString(VAL_QUAL_CD4_NM_COLUMN_NAME));
		nwisResult.setValQualCd5Nm(rs.getString(VAL_QUAL_CD5_NM_COLUMN_NAME));
		nwisResult.setRptLevVa(rs.getString(RPT_LEV_VA_COLUMN_NAME));
		nwisResult.setResultUnrndVa(rs.getString(RESULT_UNRND_VA_COLUMN_NAME));
		nwisResult.setParmMethMultiplier(rs.getString(PARM_METH_MULTIPLIER_COLUMN_NAME));
		nwisResult.setParmMultiplier(rs.getString(PARM_MULTIPLIER_COLUMN_NAME));
		nwisResult.setRptLevCd(rs.getString(RPT_LEV_CD_COLUMN_NAME));
		nwisResult.setWqxRptLevNm(rs.getString(WQX_RPT_LEV_NM_COLUMN_NAME));
		nwisResult.setPrepDt(rs.getString(PREP_DT_COLUMN_NAME));
		
		return null;
	}

}
