CREATE TABLE `QW_RESULT` (
  `sample_id` int(11) NOT NULL,
  `site_id` int(11) NOT NULL,
  `record_no` char(8) NOT NULL,
  `result_web_cd` char(1) NOT NULL,
  `parameter_cd` char(5) NOT NULL,
  `meth_cd` char(5) NOT NULL,
  `result_va` varchar(12) DEFAULT NULL,
  `result_unrnd_va` varchar(12) DEFAULT NULL,
  `result_rd` char(1) NOT NULL DEFAULT '',
  `rpt_lev_va` varchar(12) DEFAULT NULL,
  `rpt_lev_cd` char(6) NOT NULL,
  `lab_std_va` varchar(11) DEFAULT NULL,
  `remark_cd` char(1) NOT NULL,
  `val_qual_tx` char(5) NOT NULL,
  `null_val_qual_cd` char(1) NOT NULL,
  `qa_cd` char(1) NOT NULL,
  `dqi_cd` char(1) NOT NULL,
  `anl_ent_cd` char(8) NOT NULL,
  `anl_set_no` char(12) NOT NULL,
  `anl_dt` varchar(19) DEFAULT NULL,
  `prep_set_no` char(12) NOT NULL,
  `prep_dt` varchar(19) DEFAULT NULL,
  `result_field_cm_tx` varchar(300) NOT NULL,
  `result_lab_cm_tx` varchar(300) NOT NULL,
  `result_md` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `qw_result_md` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `QW_RESULT1_PK_IX` (`sample_id`,`parameter_cd`,`meth_cd`),
  KEY `QW_RESULT1_PK_2X` (`site_id`),
  KEY `QW_RESULT1_PK_3X` (`record_no`),
  KEY `QW_RESULT1_PK_6X` (`parameter_cd`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1